#!/usr/bin/env sh

#yabai -m config layout float

yabai -m rule --add app="^System Preferences" manage=off 
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^qutebrowser$" manage=on sticky=on grid=4:4:1:1:2:2

#Space 1
yabai -m rule --add app="^Code$" space=1
yabai -m rule --add app="^Emacs$" manage=on space=2 
yabai -m rule --add title=".*Capture.*" display='^1' space="^2" label="Emacs Capture Frame" sticky=on manage=off
yabai -m rule --add app="^Authy$" manage=off  layer=above  space=4
yabai -m rule --add app="^Safari$" space=4
yabai -m rule --add app="^Google Chrome$" space=5
yabai -m rule --add app="^Finder$" space=6
yabai -m rule --add app="^Postman$" space=8

#Space 2
yabai -m rule --add app="^Slack$" space=10
yabai -m rule --add app="^zoom.us$" title="Zoom" space=13
yabai -m rule --add app="^zoom.us$" title="Zoom Meeting.*" space=12

#yabai -m config --space 2 layout float
# global settings
yabai -m config status_bar                   on
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
# move mouse to focused window
yabai -m config mouse_follows_focus          off
#yabai -m config window_placement first_child
yabai -m config window_placement             second_child
# floating windows always stay on top
yabai -m config window_topmost               on
# enable borders
yabai -m config window_border                on
# no clue what this is
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config split_type                  vertical
# don't automatically rebalance windows
yabai -m config auto_balance                 on
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config window_animation_duration   0.00
# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               5
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   5

# SIP Required
# prevent border from being under the active window
yabai -m config active_window_border_topmost on
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xffff3050
yabai -m config normal_window_border_color   0xffaaaaaa
yabai -m config window_border_blur off

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise
# set mouse follows focus mode (default: off)
#yabai -m config mouse_follows_focus on

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:20:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:20:10


# Refresh spaces widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh spaces widget on display focus change
yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh spaces widget on window resize
yabai -m signal --add event=window_resized action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# Refresh process widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# Refresh process widget on when focused application changes
yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when focused application changes
yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when focused application changes
yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when focused application changes
yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# Refresh spaces widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget when current window title changes
yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

display=[^]<DISPLAY_SEL>
space=[^]<SPACE_SEL>
